sudo: required
services:
  - docker

before_install:
  - docker build -t italoferreira/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true italoferreira/react-test npm test -- --coverage

after_success:
  - docker build -t italoferreira/multi-client ./client 
  - docker build -t italoferreira/multi-nginx ./nginx 
  - docker build -t italoferreira/multi-server ./server 
  - docker build -t italoferreira/multi-worker ./worker 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push italoferreira/multi-client
  - docker push italoferreira/multi-nginx
  - docker push italoferreira/multi-server
  - docker push italoferreira/multi-worker